import Foundation

struct Country: Identifiable {
    let id = UUID()
    let name: String
    let flag: String
    let latitude: Double
    let longitude: Double
}

let allCountries: [Country] = [
    // Africa
    Country(name: "Algeria", flag: "🇩🇿", latitude: 28.03, longitude: 1.66),
    Country(name: "Angola", flag: "🇦🇴", latitude: -11.20, longitude: 17.87),
    Country(name: "Benin", flag: "🇧🇯", latitude: 9.31, longitude: 2.31),
    Country(name: "Botswana", flag: "🇧🇼", latitude: -22.33, longitude: 24.68),
    Country(name: "Burkina Faso", flag: "🇧🇫", latitude: 12.24, longitude: -1.56),
    Country(name: "Burundi", flag: "🇧🇮", latitude: -3.37, longitude: 29.92),
    Country(name: "Cameroon", flag: "🇨🇲", latitude: 7.37, longitude: 12.35),
    Country(name: "Cape Verde", flag: "🇨🇻", latitude: 16.00, longitude: -24.01),
    Country(name: "Central African Republic", flag: "🇨🇫", latitude: 6.61, longitude: 20.94),
    Country(name: "Chad", flag: "🇹🇩", latitude: 15.45, longitude: 18.73),
    Country(name: "Comoros", flag: "🇰🇲", latitude: -11.88, longitude: 43.87),
    Country(name: "Congo", flag: "🇨🇬", latitude: -0.23, longitude: 15.83),
    Country(name: "DR Congo", flag: "🇨🇩", latitude: -4.04, longitude: 21.76),
    Country(name: "Djibouti", flag: "🇩🇯", latitude: 11.83, longitude: 42.59),
    Country(name: "Egypt", flag: "🇪🇬", latitude: 26.82, longitude: 30.80),
    Country(name: "Equatorial Guinea", flag: "🇬🇶", latitude: 1.65, longitude: 10.27),
    Country(name: "Eritrea", flag: "🇪🇷", latitude: 15.18, longitude: 39.78),
    Country(name: "Eswatini", flag: "🇸🇿", latitude: -26.52, longitude: 31.47),
    Country(name: "Ethiopia", flag: "🇪🇹", latitude: 9.14, longitude: 40.49),
    Country(name: "Gabon", flag: "🇬🇦", latitude: -0.80, longitude: 11.61),
    Country(name: "Gambia", flag: "🇬🇲", latitude: 13.44, longitude: -15.31),
    Country(name: "Ghana", flag: "🇬🇭", latitude: 7.95, longitude: -1.02),
    Country(name: "Guinea", flag: "🇬🇳", latitude: 9.95, longitude: -9.70),
    Country(name: "Guinea-Bissau", flag: "🇬🇼", latitude: 11.80, longitude: -15.18),
    Country(name: "Ivory Coast", flag: "🇨🇮", latitude: 7.54, longitude: -5.55),
    Country(name: "Kenya", flag: "🇰🇪", latitude: -0.02, longitude: 37.91),
    Country(name: "Lesotho", flag: "🇱🇸", latitude: -29.61, longitude: 28.23),
    Country(name: "Liberia", flag: "🇱🇷", latitude: 6.43, longitude: -9.43),
    Country(name: "Libya", flag: "🇱🇾", latitude: 26.34, longitude: 17.23),
    Country(name: "Madagascar", flag: "🇲🇬", latitude: -18.77, longitude: 46.87),
    Country(name: "Malawi", flag: "🇲🇼", latitude: -13.25, longitude: 34.30),
    Country(name: "Mali", flag: "🇲🇱", latitude: 17.57, longitude: -4.00),
    Country(name: "Mauritania", flag: "🇲🇷", latitude: 21.01, longitude: -10.94),
    Country(name: "Mauritius", flag: "🇲🇺", latitude: -20.35, longitude: 57.55),
    Country(name: "Morocco", flag: "🇲🇦", latitude: 31.79, longitude: -7.09),
    Country(name: "Mozambique", flag: "🇲🇿", latitude: -18.67, longitude: 35.53),
    Country(name: "Namibia", flag: "🇳🇦", latitude: -22.96, longitude: 18.49),
    Country(name: "Niger", flag: "🇳🇪", latitude: 17.61, longitude: 8.08),
    Country(name: "Nigeria", flag: "🇳🇬", latitude: 9.08, longitude: 8.68),
    Country(name: "Rwanda", flag: "🇷🇼", latitude: -1.94, longitude: 29.87),
    Country(name: "São Tomé and Príncipe", flag: "🇸🇹", latitude: 0.19, longitude: 6.61),
    Country(name: "Senegal", flag: "🇸🇳", latitude: 14.50, longitude: -14.45),
    Country(name: "Seychelles", flag: "🇸🇨", latitude: -4.68, longitude: 55.49),
    Country(name: "Sierra Leone", flag: "🇸🇱", latitude: 8.46, longitude: -11.78),
    Country(name: "Somalia", flag: "🇸🇴", latitude: 5.15, longitude: 46.20),
    Country(name: "South Africa", flag: "🇿🇦", latitude: -30.56, longitude: 22.94),
    Country(name: "South Sudan", flag: "🇸🇸", latitude: 6.88, longitude: 31.31),
    Country(name: "Sudan", flag: "🇸🇩", latitude: 12.86, longitude: 30.22),
    Country(name: "Tanzania", flag: "🇹🇿", latitude: -6.37, longitude: 34.89),
    Country(name: "Togo", flag: "🇹🇬", latitude: 8.62, longitude: 0.82),
    Country(name: "Tunisia", flag: "🇹🇳", latitude: 33.89, longitude: 9.54),
    Country(name: "Uganda", flag: "🇺🇬", latitude: 1.37, longitude: 32.29),
    Country(name: "Zambia", flag: "🇿🇲", latitude: -13.13, longitude: 27.85),
    Country(name: "Zimbabwe", flag: "🇿🇼", latitude: -19.02, longitude: 29.15),

    // Americas
    Country(name: "Antigua and Barbuda", flag: "🇦🇬", latitude: 17.06, longitude: -61.80),
    Country(name: "Argentina", flag: "🇦🇷", latitude: -38.42, longitude: -63.62),
    Country(name: "Bahamas", flag: "🇧🇸", latitude: 25.03, longitude: -77.40),
    Country(name: "Barbados", flag: "🇧🇧", latitude: 13.19, longitude: -59.54),
    Country(name: "Belize", flag: "🇧🇿", latitude: 17.19, longitude: -88.50),
    Country(name: "Bolivia", flag: "🇧🇴", latitude: -16.29, longitude: -63.59),
    Country(name: "Brazil", flag: "🇧🇷", latitude: -14.24, longitude: -51.93),
    Country(name: "Canada", flag: "🇨🇦", latitude: 56.13, longitude: -106.35),
    Country(name: "Chile", flag: "🇨🇱", latitude: -35.68, longitude: -71.54),
    Country(name: "Colombia", flag: "🇨🇴", latitude: 4.57, longitude: -74.30),
    Country(name: "Costa Rica", flag: "🇨🇷", latitude: 9.75, longitude: -83.75),
    Country(name: "Cuba", flag: "🇨🇺", latitude: 21.52, longitude: -77.78),
    Country(name: "Dominica", flag: "🇩🇲", latitude: 15.41, longitude: -61.37),
    Country(name: "Dominican Republic", flag: "🇩🇴", latitude: 18.74, longitude: -70.16),
    Country(name: "Ecuador", flag: "🇪🇨", latitude: -1.83, longitude: -78.18),
    Country(name: "El Salvador", flag: "🇸🇻", latitude: 13.79, longitude: -88.90),
    Country(name: "Grenada", flag: "🇬🇩", latitude: 12.12, longitude: -61.68),
    Country(name: "Guatemala", flag: "🇬🇹", latitude: 15.78, longitude: -90.23),
    Country(name: "Guyana", flag: "🇬🇾", latitude: 4.86, longitude: -58.93),
    Country(name: "Haiti", flag: "🇭🇹", latitude: 18.97, longitude: -72.29),
    Country(name: "Honduras", flag: "🇭🇳", latitude: 15.20, longitude: -86.24),
    Country(name: "Jamaica", flag: "🇯🇲", latitude: 18.11, longitude: -77.30),
    Country(name: "Mexico", flag: "🇲🇽", latitude: 23.63, longitude: -102.55),
    Country(name: "Nicaragua", flag: "🇳🇮", latitude: 12.87, longitude: -85.21),
    Country(name: "Panama", flag: "🇵🇦", latitude: 8.54, longitude: -80.78),
    Country(name: "Paraguay", flag: "🇵🇾", latitude: -23.44, longitude: -58.44),
    Country(name: "Peru", flag: "🇵🇪", latitude: -9.19, longitude: -75.02),
    Country(name: "Saint Kitts and Nevis", flag: "🇰🇳", latitude: 17.36, longitude: -62.78),
    Country(name: "Saint Lucia", flag: "🇱🇨", latitude: 13.91, longitude: -60.98),
    Country(name: "Saint Vincent", flag: "🇻🇨", latitude: 12.98, longitude: -61.29),
    Country(name: "Suriname", flag: "🇸🇷", latitude: 3.92, longitude: -56.03),
    Country(name: "Trinidad and Tobago", flag: "🇹🇹", latitude: 10.69, longitude: -61.22),
    Country(name: "United States", flag: "🇺🇸", latitude: 37.09, longitude: -95.71),
    Country(name: "Uruguay", flag: "🇺🇾", latitude: -32.52, longitude: -55.77),
    Country(name: "Venezuela", flag: "🇻🇪", latitude: 6.42, longitude: -66.59),

    // Asia
    Country(name: "Afghanistan", flag: "🇦🇫", latitude: 33.94, longitude: 67.71),
    Country(name: "Armenia", flag: "🇦🇲", latitude: 40.07, longitude: 45.04),
    Country(name: "Azerbaijan", flag: "🇦🇿", latitude: 40.14, longitude: 47.58),
    Country(name: "Bahrain", flag: "🇧🇭", latitude: 25.93, longitude: 50.64),
    Country(name: "Bangladesh", flag: "🇧🇩", latitude: 23.68, longitude: 90.36),
    Country(name: "Bhutan", flag: "🇧🇹", latitude: 27.51, longitude: 90.43),
    Country(name: "Brunei", flag: "🇧🇳", latitude: 4.54, longitude: 114.73),
    Country(name: "Cambodia", flag: "🇰🇭", latitude: 12.57, longitude: 104.99),
    Country(name: "China", flag: "🇨🇳", latitude: 35.86, longitude: 104.20),
    Country(name: "Georgia", flag: "🇬🇪", latitude: 42.32, longitude: 43.36),
    Country(name: "India", flag: "🇮🇳", latitude: 20.59, longitude: 78.96),
    Country(name: "Indonesia", flag: "🇮🇩", latitude: -0.79, longitude: 113.92),
    Country(name: "Iran", flag: "🇮🇷", latitude: 32.43, longitude: 53.69),
    Country(name: "Iraq", flag: "🇮🇶", latitude: 33.22, longitude: 43.68),
    Country(name: "Israel", flag: "🇮🇱", latitude: 31.05, longitude: 34.85),
    Country(name: "Japan", flag: "🇯🇵", latitude: 36.20, longitude: 138.25),
    Country(name: "Jordan", flag: "🇯🇴", latitude: 30.59, longitude: 36.24),
    Country(name: "Kazakhstan", flag: "🇰🇿", latitude: 48.02, longitude: 66.92),
    Country(name: "Kuwait", flag: "🇰🇼", latitude: 29.31, longitude: 47.48),
    Country(name: "Kyrgyzstan", flag: "🇰🇬", latitude: 41.20, longitude: 74.77),
    Country(name: "Laos", flag: "🇱🇦", latitude: 19.86, longitude: 102.50),
    Country(name: "Lebanon", flag: "🇱🇧", latitude: 33.85, longitude: 35.86),
    Country(name: "Malaysia", flag: "🇲🇾", latitude: 4.21, longitude: 101.98),
    Country(name: "Maldives", flag: "🇲🇻", latitude: 3.20, longitude: 73.22),
    Country(name: "Mongolia", flag: "🇲🇳", latitude: 46.86, longitude: 103.85),
    Country(name: "Myanmar", flag: "🇲🇲", latitude: 21.91, longitude: 95.96),
    Country(name: "Nepal", flag: "🇳🇵", latitude: 28.39, longitude: 84.12),
    Country(name: "North Korea", flag: "🇰🇵", latitude: 40.34, longitude: 127.51),
    Country(name: "Oman", flag: "🇴🇲", latitude: 21.47, longitude: 55.98),
    Country(name: "Pakistan", flag: "🇵🇰", latitude: 30.38, longitude: 69.35),
    Country(name: "Palestine", flag: "🇵🇸", latitude: 31.95, longitude: 35.23),
    Country(name: "Philippines", flag: "🇵🇭", latitude: 12.88, longitude: 121.77),
    Country(name: "Qatar", flag: "🇶🇦", latitude: 25.35, longitude: 51.18),
    Country(name: "Saudi Arabia", flag: "🇸🇦", latitude: 23.89, longitude: 45.08),
    Country(name: "Singapore", flag: "🇸🇬", latitude: 1.35, longitude: 103.82),
    Country(name: "South Korea", flag: "🇰🇷", latitude: 35.91, longitude: 127.77),
    Country(name: "Sri Lanka", flag: "🇱🇰", latitude: 7.87, longitude: 80.77),
    Country(name: "Syria", flag: "🇸🇾", latitude: 34.80, longitude: 38.99),
    Country(name: "Taiwan", flag: "🇹🇼", latitude: 23.70, longitude: 120.96),
    Country(name: "Tajikistan", flag: "🇹🇯", latitude: 38.86, longitude: 71.28),
    Country(name: "Thailand", flag: "🇹🇭", latitude: 15.87, longitude: 100.99),
    Country(name: "Timor-Leste", flag: "🇹🇱", latitude: -8.87, longitude: 125.73),
    Country(name: "Turkey", flag: "🇹🇷", latitude: 38.96, longitude: 35.24),
    Country(name: "Turkmenistan", flag: "🇹🇲", latitude: 38.97, longitude: 59.56),
    Country(name: "United Arab Emirates", flag: "🇦🇪", latitude: 23.42, longitude: 53.85),
    Country(name: "Uzbekistan", flag: "🇺🇿", latitude: 41.38, longitude: 64.59),
    Country(name: "Vietnam", flag: "🇻🇳", latitude: 14.06, longitude: 108.28),
    Country(name: "Yemen", flag: "🇾🇪", latitude: 15.55, longitude: 48.52),

    // Europe
    Country(name: "Albania", flag: "🇦🇱", latitude: 41.15, longitude: 20.17),
    Country(name: "Andorra", flag: "🇦🇩", latitude: 42.55, longitude: 1.60),
    Country(name: "Austria", flag: "🇦🇹", latitude: 47.52, longitude: 14.55),
    Country(name: "Belarus", flag: "🇧🇾", latitude: 53.71, longitude: 27.95),
    Country(name: "Belgium", flag: "🇧🇪", latitude: 50.50, longitude: 4.47),
    Country(name: "Bosnia and Herzegovina", flag: "🇧🇦", latitude: 43.92, longitude: 17.68),
    Country(name: "Bulgaria", flag: "🇧🇬", latitude: 42.73, longitude: 25.49),
    Country(name: "Croatia", flag: "🇭🇷", latitude: 45.10, longitude: 15.20),
    Country(name: "Cyprus", flag: "🇨🇾", latitude: 35.13, longitude: 33.43),
    Country(name: "Czech Republic", flag: "🇨🇿", latitude: 49.82, longitude: 15.47),
    Country(name: "Denmark", flag: "🇩🇰", latitude: 56.26, longitude: 9.50),
    Country(name: "Estonia", flag: "🇪🇪", latitude: 58.60, longitude: 25.01),
    Country(name: "Finland", flag: "🇫🇮", latitude: 61.92, longitude: 25.75),
    Country(name: "France", flag: "🇫🇷", latitude: 46.23, longitude: 2.21),
    Country(name: "Germany", flag: "🇩🇪", latitude: 51.17, longitude: 10.45),
    Country(name: "Greece", flag: "🇬🇷", latitude: 39.07, longitude: 21.82),
    Country(name: "Hungary", flag: "🇭🇺", latitude: 47.16, longitude: 19.50),
    Country(name: "Iceland", flag: "🇮🇸", latitude: 64.96, longitude: -19.02),
    Country(name: "Ireland", flag: "🇮🇪", latitude: 53.14, longitude: -7.69),
    Country(name: "Italy", flag: "🇮🇹", latitude: 41.87, longitude: 12.57),
    Country(name: "Kosovo", flag: "🇽🇰", latitude: 42.60, longitude: 20.90),
    Country(name: "Latvia", flag: "🇱🇻", latitude: 56.88, longitude: 24.60),
    Country(name: "Liechtenstein", flag: "🇱🇮", latitude: 47.17, longitude: 9.55),
    Country(name: "Lithuania", flag: "🇱🇹", latitude: 55.17, longitude: 23.88),
    Country(name: "Luxembourg", flag: "🇱🇺", latitude: 49.82, longitude: 6.13),
    Country(name: "Malta", flag: "🇲🇹", latitude: 35.94, longitude: 14.38),
    Country(name: "Moldova", flag: "🇲🇩", latitude: 47.41, longitude: 28.37),
    Country(name: "Monaco", flag: "🇲🇨", latitude: 43.75, longitude: 7.41),
    Country(name: "Montenegro", flag: "🇲🇪", latitude: 42.71, longitude: 19.37),
    Country(name: "Netherlands", flag: "🇳🇱", latitude: 52.13, longitude: 5.29),
    Country(name: "North Macedonia", flag: "🇲🇰", latitude: 41.51, longitude: 21.75),
    Country(name: "Norway", flag: "🇳🇴", latitude: 60.47, longitude: 8.47),
    Country(name: "Poland", flag: "🇵🇱", latitude: 51.92, longitude: 19.15),
    Country(name: "Portugal", flag: "🇵🇹", latitude: 39.40, longitude: -8.22),
    Country(name: "Romania", flag: "🇷🇴", latitude: 45.94, longitude: 24.97),
    Country(name: "Russia", flag: "🇷🇺", latitude: 61.52, longitude: 105.32),
    Country(name: "San Marino", flag: "🇸🇲", latitude: 43.94, longitude: 12.46),
    Country(name: "Serbia", flag: "🇷🇸", latitude: 44.02, longitude: 21.01),
    Country(name: "Slovakia", flag: "🇸🇰", latitude: 48.67, longitude: 19.70),
    Country(name: "Slovenia", flag: "🇸🇮", latitude: 46.15, longitude: 14.99),
    Country(name: "Spain", flag: "🇪🇸", latitude: 40.46, longitude: -3.75),
    Country(name: "Sweden", flag: "🇸🇪", latitude: 60.13, longitude: 18.64),
    Country(name: "Switzerland", flag: "🇨🇭", latitude: 46.82, longitude: 8.23),
    Country(name: "Ukraine", flag: "🇺🇦", latitude: 48.38, longitude: 31.17),
    Country(name: "United Kingdom", flag: "🇬🇧", latitude: 55.38, longitude: -3.44),
    Country(name: "Vatican City", flag: "🇻🇦", latitude: 41.90, longitude: 12.45),

    // Oceania
    Country(name: "Australia", flag: "🇦🇺", latitude: -25.27, longitude: 133.78),
    Country(name: "Fiji", flag: "🇫🇯", latitude: -17.71, longitude: 178.07),
    Country(name: "Kiribati", flag: "🇰🇮", latitude: -3.37, longitude: -168.73),
    Country(name: "Marshall Islands", flag: "🇲🇭", latitude: 7.13, longitude: 171.18),
    Country(name: "Micronesia", flag: "🇫🇲", latitude: 7.43, longitude: 150.55),
    Country(name: "Nauru", flag: "🇳🇷", latitude: -0.52, longitude: 166.93),
    Country(name: "New Zealand", flag: "🇳🇿", latitude: -40.90, longitude: 174.89),
    Country(name: "Palau", flag: "🇵🇼", latitude: 7.51, longitude: 134.58),
    Country(name: "Papua New Guinea", flag: "🇵🇬", latitude: -6.31, longitude: 143.96),
    Country(name: "Samoa", flag: "🇼🇸", latitude: -13.76, longitude: -172.10),
    Country(name: "Solomon Islands", flag: "🇸🇧", latitude: -9.65, longitude: 160.16),
    Country(name: "Tonga", flag: "🇹🇴", latitude: -21.18, longitude: -175.20),
    Country(name: "Tuvalu", flag: "🇹🇻", latitude: -7.11, longitude: 177.65),
    Country(name: "Vanuatu", flag: "🇻🇺", latitude: -15.38, longitude: 166.96),
]
